language: php

php:
  - hhvm
  - 7.2
  - 7.3
  - 7.4

addons:
  chrome: stable
  
env:
  global:
    CC_TEST_REPORTER_ID=0f7f9966b951b24b5b22bbdfa16ffd5653d7b038fc9db33b66c102a7e08aee63

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
install:
  - composer update
  
script:
  - php bin/phpunit
  
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
